### ISSUE TITLE
Custom Sounds Client side

### ISSUE THREAD

**Issue by FadedDay** [clementinise/CustomSounds#1]
Lethal v45

I'm using the Custom sounds mod v1.3 and LcSoundtool with no other mods. I am unable to join public lobbies. Is there a config I need to edit or does the mod not work client-side only?

**Comment by LukarioMC** [comment]
My friend too is also finding it difficult to join my lobby when all of the other sound mods used are client-sided, but CustomSounds itself is not. When attempting to join my lobby it throws "An error occurred" and puts him back to the main menu. Is there a way to fix this compatibility?

**Comment by clementinise** [comment]
> My friend too is also finding it difficult to join my lobby when all of the other sound mods used are client-sided, but CustomSounds itself is not. When attempting to join my lobby it throws "An error occurred" and puts him back to the main menu. Is there a way to fix this compatibility?

You need to set `EnableNetworking` in the config file for CustomSounds to false so your friend can join your session without CustomSounds installed
