### ISSUE TITLE
Newest Update Broken

### ISSUE THREAD

**Issue by TheMasterKy** [clementinise/CustomSounds#12]
![image](https://github.com/clementinise/CustomSounds/assets/146745744/f26c829f-5b53-4ea3-86ec-75f57387b421)
![image](https://github.com/clementinise/CustomSounds/assets/146745744/036d76c2-e570-4d68-b520-91653911f921)
No matter what I do, I get these issues after updating everything. Someone explain?

**Comment by burnttapwater** [comment]
having the same problem just reinstall the previous version and dont update till its fixed

**Comment by clementinise** [comment]
Does putting the audio in sub-folders fixes this issue?

**Comment by Hopeman96** [comment]
i made a Chitter1-AS folder and no it didnt fix the issue. same error text.

**Comment by TheMasterKy** [comment]
Spoke to Clementinise and helped debug the issue. Hopefully soon a hotfix will be pushed.

**Comment by clementinise** [comment]
Hotfix release on Thunderstore, Github will soon be updated too!
