### ISSUE TITLE
1.3.+ Random sounds don't work

### ISSUE THREAD

**Issue by huluoboya3** [clementinise/CustomSounds#13]
use mod
-LCSoundTool1.5.0
-CustomSounds

The terminal has shown loading
But only the first audio can be played, not randomly
OGG/MP3/WAV cannot be used together
Sometimes the audio won't be replaced

(https://i.postimg.cc/V6LZ3gKC/QQ-20240119054507.png)

**Comment by clementinise** [comment]
This issue can't be resolved on my end. Please wait for an update to LCSoundTool 👍
