### ISSUE TITLE
Sounds not playin

### ISSUE THREAD

**Issue by Hopeman96** [clementinise/CustomSounds#14]
My Sounds are all Shown in CustomSounds list but none of it is playing. it always plays the default sound, tho it did work before without changing anything.
Thats why i tried only to have BepInEx LCSoundTool CustomSounds and just one Personal Sample. 
The manifest and Everything is ok i cecked it 4 times, but it alwas plays default game sounds.

**Comment by clementinise** [comment]
Set `HideManagerGameObject` to "true" in Bepinex.cfg
`HideManagerGameObject` will be automatically set to "true" in a coming hot fix
