### ISSUE TITLE
Sounds do not work in the assembly of mods, any

### ISSUE THREAD

**Issue by Paradox75831004** [clementinise/CustomSounds#15]
It just doesn't work and that's it, no matter how much r2modman installs through the application - it doesn't pick up sounds, why?
Build mods - 018d419c-CD81-a9e2-1700-42ec8428ba54

**Comment by clementinise** [comment]
Can you further explain what doesn't work?

**Comment by Paradox75831004** [comment]
Everything is already fine, it is working stably. Some updates have happened and everything has turned on
