### ISSUE TITLE
 ArgumentException: Undefined target method for patch method static void CustomSounds.Patches.RemapKeyPatch::AddRemappableKey(KepRemapPanel __instance)

### ISSUE THREAD

**Issue by rogedkone** [clementinise/CustomSounds#2]
ArgumentException: Undefined target method for patch method static void CustomSounds.Patches.RemapKeyPatch::AddRemappableKey(KepRemapPanel __instance)
 
 2.2.0 - broken
 2.1.2 - work
![image](https://github.com/clementinise/CustomSounds/assets/85563010/563307e6-4d33-4bb4-89cb-5e3e1ed505da)

**Comment by clementinise** [comment]
Are you on the latest update of V45?

**Comment by rogedkone** [comment]
yes
