### ISSUE TITLE
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: ShovelSwing-fuk-you-25 

### ISSUE THREAD

**Issue by ShatterDive** [clementinise/CustomSounds#3]
The issue appears when trying to replace the shovelSwing sound and sync in mutiplayer
LCSoundTool: 1.4.0
CustomSounds: 2.2.0
BepInExPack: 5.4.2100
![image](https://github.com/clementinise/CustomSounds/assets/127084205/f5fb2c46-21cd-4606-ba31-03d13bb52217)

**Comment by clementinise** [comment]
Do you have two files with the same name or same percentage?

**Comment by ShatterDive** [comment]
in the folder only has 1 file.

**Comment by clementinise** [comment]
I will add a debug mode in the next update, because I have no idea

**Comment by Danice123** [comment]
Something is fundamentally broken here. I can replicate this in multiple ways:
(Tested with no other mods but custom sounds and dependancies loaded)

`customsounds reload` at any time when there is a custom sound loaded except the first time a sound is loaded. Command works fine when the folder is empty. No errors on game boot and sound overrides work correctly locally. And if you boot with nothing in the custom sound folder, you can reload to hot load new sounds, but the second invocation will fail with this error. Also loading a sound, removing it and reloading an empty folder, then adding the sound back will also cause this error.

`customsounds sync` just always causes this error when there is a custom sound.

**Comment by Danice123** [comment]
Actually think this is an issue with LCSoundTool not handling this mod's use case correctly, opened
https://github.com/no00ob/LCSoundTool/issues/6

Likely LCSoundTool 1.3.2 works, downgrading to that should band aid the issue

**Comment by susy-bakaa** [comment]
I merged the fix by @Danice123 and it will be out in the next update, which should hopefully be in the next few days.
