### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by Danice123** [clementinise/CustomSounds#4]
It would be really nice to support MP3's here too, since the file size will be much smaller. LCSoundTool supports MP3s and OGGs now so this should be a rather easy add.

Alternatively if you commit your solution files I'll submit a feature branch, but at the moment I can't get this project to build correctly locally.

**Comment by clementinise** [comment]
I was away for the holidays, but I'll update it as soon as I can!

**Comment by clementinise** [comment]
Update release on Thunderstore, Github will soon be updated too!
