### ISSUE TITLE
Custom sounds refuse to work

### ISSUE THREAD

**Issue by user7562** [clementinise/CustomSounds#7]
i have modified some sounds of the game and they refuse to work, the majority of them work but sometimes the mod bugs out and most sounds stop working, they are the same bitrate and stereo. help?

**Comment by rainbow137** [comment]
It seems that you need to place the custom audio in the "customsound" folder and the required format should be WAV. Currently, I've renamed it like this: "pop.WAV," with an uppercase suffix.
I'm not sure if it's effective.

**Comment by user7562** [comment]
The sound file is in customsounds and its in the wav file format

**Comment by user7562** [comment]
the sound files are located in CustomSounds>[name of my folder]>here, they are wav formats. same bitrate as the original and same file name as the original and they are stereo like the original, and yet some of them refuse to work, its either completely muted or it just resets to the default sound
