### ISSUE TITLE
Is it possible to have multiple sounds for e.g the rocket? and randomize?

### ISSUE THREAD

**Issue by Froddish** [clementinise/CustomSounds#8]
As the title says, there is a mod named "randomsounds" that has this feature but i can't make my "own mod" for that mod as easy as this customsounds mod.

Is it possible to add a randomizer feature?

**Comment by clementinise** [comment]
You can use random sounds, it's an effecient way of adding more sounds to one audioclip
Just add `_{percentage}` add the end of any sounds, like `JackOLanternHit_50` (50% chance for this sound to play for `JackOLanternHit` AudioClip)

**Comment by Froddish** [comment]
Hello! thank you!

I didn't get it to work first but i found this comment in LCsoundtool
1.3.1

Changed the random clip seperator from "_" to "-".

maybe it will work now :)
